### ISSUE TITLE
Demo Broken

### ISSUE THREAD

**Issue by COLABORATI** [yetkinozturk/ITSY#7]
Navigation seems to be broken in the demo. I will never understand why people do not care for their demos. The demo is important, if it breaks, nobody will look into your project.

**Comment by pahaz** [comment]
I have the problem too

**Comment by nickliqian** [comment]
I also have the problem, maybe nobody work for this project right now.

**Comment by yetkinozturk** [comment]
it seems i didn't pay the hosting fee. I think i will not.

**Comment by nickliqian** [comment]
Get it, maybe it is better if there are several pictures about this project on `readme.md` file. The first time visitors see these pictures, they will understand what the project can do, especially in non-english speaking countries. Thank you very much for your contribution to your project !!!
